services:
  multi_languages_website:
    build: .
    container_name: multi_languages_website
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.multi_languages_website.entrypoints: https
      
      traefik.http.routers.multi_languages_website.rule: Host(`yourdomain.com`)
      traefik.http.routers.multi_languages_website.tls: true
      traefik.http.routers.multi_languages_website.service: multi_languages_website
      traefik.http.services.multi_languages_website.loadbalancer.server.port: yourport
      traefik.docker.network: proxy
    networks:
      - proxy

networks:
  proxy:
    external: true